fail_fast: true
repos:
- repo: local
  hooks:
  - id: update
    name: update
    entry: dotfiles-update
    language: system
    always_run: true
    pass_filenames: false
    description: update
    verbose: true
  - id: dump
    name: dump
    entry: dotfiles-dump
    language: system
    always_run: false
    pass_filenames: false
    description: dump
    verbose: true
- repo: https://github.com/gitguardian/ggshield
  rev: v1.11.0
  hooks:
  - id: ggshield
    language_version: python3
    stages: [commit]
