tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/core", "/Users/stanb/.brew_cache/homebrew-core"
tap "teamookla/speedtest"
brew "coreutils"
brew "libogg"
brew "libsndfile"
brew "ffmpeg"
brew "fzf"
brew "git-lfs"
brew "gnupg"
brew "htop"
brew "lsd"
brew "mas"
brew "mpv"
brew "ncdu"
brew "neofetch"
brew "nnn"
brew "rclone"
brew "subversion"
brew "tldr"
brew "tmux"
brew "tree"
brew "wget"
brew "teamookla/speedtest/speedtest"
cask "alfred"
cask "amethyst"
cask "daisydisk"
cask "dash"
cask "flux"
cask "font-hack-nerd-font"
cask "font-source-code-pro"
cask "google-chrome"
cask "iterm2"
cask "jetbrains-toolbox"
cask "macdown"
cask "mendeley"
cask "microsoft-auto-update"
cask "microsoft-powerpoint"
cask "microsoft-word"
cask "miro"
cask "mountain-duck"
cask "notion"
cask "obsidian"
cask "slack"
cask "spotify"
cask "telegram"
cask "the-unarchiver"
cask "ticktick"
cask "zoom"
mas "Bear", id: 1091189122
mas "GoodNotes", id: 1444383602
mas "Magnet", id: 441258766
mas "SnippetsLab", id: 1006087419
mas "Tomato 2", id: 1494210770
mas "Trello", id: 1278508951
mas "Xcode", id: 497799835
